# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: student.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rstudent.proto\x12\x07student\"\x0c\n\nGetRequest\"5\n\x08GetReply\x12)\n\x0bStudentList\x18\x01 \x01(\x0b\x32\x14.student.StudentList\"+\n\x0b\x43ontactInfo\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\r\n\x05phone\x18\x02 \x01(\t\"C\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\"=\n\x06\x43ourse\x12\x10\n\x08\x63ourseId\x18\x01 \x01(\t\x12\x12\n\ncourseName\x18\x02 \x01(\t\x12\r\n\x05grade\x18\x03 \x01(\t\"Z\n\x0c\x41\x63\x61\x64\x65micInfo\x12\r\n\x05major\x18\x01 \x01(\t\x12\x0c\n\x04year\x18\x02 \x01(\t\x12\x0b\n\x03gpa\x18\x03 \x01(\x01\x12 \n\x07\x63ourses\x18\x04 \x03(\x0b\x32\x0f.student.Course\"Q\n\x17\x45xtracurricularActivity\x12\x12\n\nactivityId\x18\x01 \x01(\x05\x12\x14\n\x0c\x61\x63tivityName\x18\x02 \x01(\t\x12\x0c\n\x04role\x18\x03 \x01(\t\"\x97\x02\n\x07Student\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tfirstName\x18\x02 \x01(\t\x12\x10\n\x08lastName\x18\x03 \x01(\t\x12\x0b\n\x03\x61ge\x18\x04 \x01(\x05\x12\x0e\n\x06gender\x18\x05 \x01(\t\x12)\n\x0b\x63ontactInfo\x18\x06 \x01(\x0b\x32\x14.student.ContactInfo\x12!\n\x07\x61\x64\x64ress\x18\x07 \x01(\x0b\x32\x10.student.Address\x12+\n\x0c\x61\x63\x61\x64\x65micInfo\x18\x08 \x01(\x0b\x32\x15.student.AcademicInfo\x12\x43\n\x19\x65xtracurricularActivities\x18\t \x03(\x0b\x32 .student.ExtracurricularActivity\"1\n\x0bStudentList\x12\"\n\x08students\x18\x01 \x03(\x0b\x32\x10.student.Student2@\n\x0bStudentData\x12\x31\n\x07GetList\x12\x13.student.GetRequest\x1a\x11.student.GetReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'student_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETREQUEST']._serialized_start=26
  _globals['_GETREQUEST']._serialized_end=38
  _globals['_GETREPLY']._serialized_start=40
  _globals['_GETREPLY']._serialized_end=93
  _globals['_CONTACTINFO']._serialized_start=95
  _globals['_CONTACTINFO']._serialized_end=138
  _globals['_ADDRESS']._serialized_start=140
  _globals['_ADDRESS']._serialized_end=207
  _globals['_COURSE']._serialized_start=209
  _globals['_COURSE']._serialized_end=270
  _globals['_ACADEMICINFO']._serialized_start=272
  _globals['_ACADEMICINFO']._serialized_end=362
  _globals['_EXTRACURRICULARACTIVITY']._serialized_start=364
  _globals['_EXTRACURRICULARACTIVITY']._serialized_end=445
  _globals['_STUDENT']._serialized_start=448
  _globals['_STUDENT']._serialized_end=727
  _globals['_STUDENTLIST']._serialized_start=729
  _globals['_STUDENTLIST']._serialized_end=778
  _globals['_STUDENTDATA']._serialized_start=780
  _globals['_STUDENTDATA']._serialized_end=844
# @@protoc_insertion_point(module_scope)
